services:
  nginx:
    image: nginx:alpine
    volumes:
    - ./etc/nginx/conf.d:/etc/nginx/conf.d
    - ./etc/nginx/tls:/etc/nginx/tls
    - ./var/www/html:/var/www/html
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    networks:
      - default

networks:
  default:
    external: true
    name: '${APP_NETWORK:-development}'
